# https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
name: Deploy Project
on:
  push:
    branches:
      - 'master'
# every job has its own runner/vm that is isolated form the other jobs/runners
jobs:
  test:
  # need to define env/runner. It's the vm/server the code will run on
    runs-on: ubuntu-latest
    # steps execute a shell script or an action
    steps: 
      - name: Get code
      # uses is a keyword that defines the action that will be used
      # checkout allows for the entire repo to be downloaded to the runner
        uses: actions/checkout@v3
        # this is not needed b/c ubuntu latest has node already
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  deploy:
    #  using needs tells the pipeline that test needs to run successfully first
    # needs: [job1, job2]
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
